
package system;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.*;

public final class Main_page_panel extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    
    public Main_page_panel() {
        initComponents();
        powerlbl.setText(null);
        setMain();
        setIconImage(Toolkit.getDefaultToolkit().createImage("icon/icon.png"));
        setDefaultCloseOperation(Main_page_panel.DO_NOTHING_ON_CLOSE);
       addWindowListener(new WindowAdapter() {
                        @Override
			public void windowClosing(WindowEvent e) {
                            int choice = JOptionPane.showConfirmDialog(
					null, 
					"Are you sure you want to exit?", 
					"CONFIRM", 
					JOptionPane.YES_NO_OPTION
				);
				if (choice == JOptionPane.YES_OPTION) { //yes
					System.exit(0);
				}
				
			}
		});
        
        
    }
    public void setMain(){
        signout.setVisible(false);
        signoutlbl.setVisible(false);
        setting.setVisible(false);
        settinglbl.setVisible(false);
        registered.setVisible(false);
        registeredlbl.setVisible(false);
        evaluation.setVisible(false);
        evaluationlbl.setVisible(false);
        jloginbtn.setVisible(true);
        labelcon.setVisible(true);
        setSize(817,300);
        setLocationRelativeTo(null);
    }
    
    public void sameExist(){
        setVisible(true);
        setLocationRelativeTo(null);
        setSize(817,460);
        getJloginbtn().setVisible(false);
        getloginlbl().setVisible(false);
        getSignout().setVisible(true);
        getSignoutlbl().setVisible(true);
        getRegistered().setVisible(true);
        getRegisteredlbl().setVisible(true);
        getEvaluation().setVisible(true);
        getEvaluationlbl().setVisible(true);
   }
   public void forStaff(){
        sameExist();        
   }
   public void forAdmin(){
       sameExist();
       getSetting().setVisible(true);
       getSettinglbl().setVisible(true);
   }
    
    public JLabel getLabelcon(){
        return labelcon;
    }
     public JButton getSetting(){
         return setting;
     }
     public JLabel getSettinglbl(){
         return settinglbl;
     }
     public JButton getSignout(){
         return signout;
     }
     public JLabel getSignoutlbl(){
         return signoutlbl;
     }
     public JButton getRegistered(){
         return registered;
     }
     public JLabel getRegisteredlbl(){
         return registeredlbl;
     }
     public JButton getEvaluation(){
         return evaluation;
     }
     public JLabel getEvaluationlbl(){
         return evaluationlbl;
     }
     public JLabel getJloginbtn(){
         return jloginbtn;
     }
     public JLabel getloginlbl(){
         return labelcon;
     }
     public JLabel getPower(){
         return powerlbl;
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        register = new javax.swing.JButton();
        setting = new javax.swing.JButton();
        registered = new javax.swing.JButton();
        signout = new javax.swing.JButton();
        status = new javax.swing.JButton();
        evaluation = new javax.swing.JButton();
        courses = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        settinglbl = new javax.swing.JLabel();
        signoutlbl = new javax.swing.JLabel();
        evaluationlbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        registeredlbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jloginbtn = new javax.swing.JLabel();
        labelcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        powerlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/clipboard-with-pencil-.png"))); // NOI18N
        register.setBorder(null);
        register.setBorderPainted(false);
        register.setContentAreaFilled(false);
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.setFocusPainted(false);
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerMouseExited(evt);
            }
        });
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/management.png"))); // NOI18N
        setting.setBorderPainted(false);
        setting.setContentAreaFilled(false);
        setting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setting.setFocusPainted(false);
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingMouseExited(evt);
            }
        });
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });

        registered.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/cash-register.png"))); // NOI18N
        registered.setBorderPainted(false);
        registered.setContentAreaFilled(false);
        registered.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registered.setFocusPainted(false);
        registered.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registeredMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registeredMouseExited(evt);
            }
        });
        registered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredActionPerformed(evt);
            }
        });

        signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/sign-out-option.png"))); // NOI18N
        signout.setBorderPainted(false);
        signout.setContentAreaFilled(false);
        signout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signout.setFocusPainted(false);
        signout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signoutMouseExited(evt);
            }
        });
        signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutActionPerformed(evt);
            }
        });

        status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/visible-status.png"))); // NOI18N
        status.setBorderPainted(false);
        status.setContentAreaFilled(false);
        status.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        status.setFocusPainted(false);
        status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statusMouseExited(evt);
            }
        });
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        evaluation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/blogger.png"))); // NOI18N
        evaluation.setBorderPainted(false);
        evaluation.setContentAreaFilled(false);
        evaluation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        evaluation.setFocusPainted(false);
        evaluation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                evaluationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                evaluationMouseExited(evt);
            }
        });
        evaluation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluationActionPerformed(evt);
            }
        });

        courses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/online-course.png"))); // NOI18N
        courses.setBorderPainted(false);
        courses.setContentAreaFilled(false);
        courses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        courses.setFocusPainted(false);
        courses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                coursesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                coursesMouseExited(evt);
            }
        });
        courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("REGISTER");

        settinglbl.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        settinglbl.setText("SETTINGS");

        signoutlbl.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        signoutlbl.setText("SIGN OUT");

        evaluationlbl.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        evaluationlbl.setText("EVALUATION");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setText("COURSES");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setText("STATUS");

        registeredlbl.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        registeredlbl.setText("REGISTERED ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Enrollment System");

        jloginbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jloginbtn.setForeground(new java.awt.Color(0, 0, 204));
        jloginbtn.setText("Login");
        jloginbtn.setToolTipText("");
        jloginbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jloginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jloginbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jloginbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jloginbtnMouseExited(evt);
            }
        });

        labelcon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelcon.setText("to access full menu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("Level:");

        powerlbl.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        powerlbl.setText("                    ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(powerlbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registered, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(registeredlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(evaluation, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jloginbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelcon)))
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(settinglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(180, 180, 180)
                                .addComponent(signoutlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(setting, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127)
                                .addComponent(signout, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 99, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(courses, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)))))
                        .addGap(24, 24, 24)
                        .addComponent(evaluationlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jloginbtn)
                                    .addComponent(labelcon)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(powerlbl)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(evaluationlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courses, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(evaluation, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registeredlbl)
                            .addComponent(settinglbl)))
                    .addComponent(signoutlbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registered)
                    .addComponent(setting, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signout, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutActionPerformed
        setMain();
        powerlbl.setText(null);
    }//GEN-LAST:event_signoutActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        Register rgt = new Register();
        rgt.getLevel().setText(powerlbl.getText());
        rgt.setVisible(true);
        rgt.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_registerActionPerformed

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
        
    }//GEN-LAST:event_settingActionPerformed

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseEntered
        register.setBorderPainted(true);
        register.setContentAreaFilled(true);
        register.setFocusPainted(true);
        register.setOpaque(true);
    }//GEN-LAST:event_registerMouseEntered

    private void registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseExited
        register.setBorderPainted(false);
        register.setContentAreaFilled(false);
        register.setFocusPainted(false);
        register.setOpaque(false);
    }//GEN-LAST:event_registerMouseExited

    private void registeredMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registeredMouseEntered
       registered.setBorderPainted(true);
       registered.setContentAreaFilled(true);
       registered.setFocusPainted(true);
       registered.setOpaque(true);
    }//GEN-LAST:event_registeredMouseEntered

    private void registeredMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registeredMouseExited
        registered.setBorderPainted(false);
        registered.setContentAreaFilled(false);
        registered.setFocusPainted(false);
        registered.setOpaque(false);
    }//GEN-LAST:event_registeredMouseExited

    private void evaluationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evaluationMouseEntered
        evaluation.setBorderPainted(true);
        evaluation.setContentAreaFilled(true);
        evaluation.setFocusPainted(true);
        evaluation.setOpaque(true);
    }//GEN-LAST:event_evaluationMouseEntered

    private void evaluationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evaluationMouseExited
        evaluation.setBorderPainted(false);
        evaluation.setContentAreaFilled(false);
        evaluation.setFocusPainted(false);
        evaluation.setOpaque(false);
    }//GEN-LAST:event_evaluationMouseExited

    private void coursesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesMouseEntered
        courses.setBorderPainted(true);
        courses.setContentAreaFilled(true);
        courses.setFocusPainted(true);
        courses.setOpaque(true);
    }//GEN-LAST:event_coursesMouseEntered

    private void coursesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesMouseExited
        courses.setBorderPainted(false);
        courses.setContentAreaFilled(false);
        courses.setFocusPainted(false);
        courses.setOpaque(false);
    }//GEN-LAST:event_coursesMouseExited

    private void statusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMouseEntered
        status.setBorderPainted(true);
        status.setContentAreaFilled(true);
        status.setFocusPainted(true);
        status.setOpaque(true);
    }//GEN-LAST:event_statusMouseEntered

    private void statusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMouseExited
        status.setBorderPainted(false);
        status.setContentAreaFilled(false);
        status.setFocusPainted(false);
        status.setOpaque(false);
    }//GEN-LAST:event_statusMouseExited

    private void settingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseEntered
        setting.setBorderPainted(true);
        setting.setContentAreaFilled(true);
        setting.setFocusPainted(true);
        setting.setOpaque(true);
    }//GEN-LAST:event_settingMouseEntered

    private void settingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseExited
        setting.setBorderPainted(false);
        setting.setContentAreaFilled(false);
        setting.setFocusPainted(false);
        setting.setOpaque(false);
    }//GEN-LAST:event_settingMouseExited

    private void signoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutMouseEntered
        signout.setBorderPainted(true);
        signout.setContentAreaFilled(true);
        signout.setFocusPainted(true);
        signout.setOpaque(true);
    }//GEN-LAST:event_signoutMouseEntered

    private void signoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutMouseExited
        signout.setBorderPainted(false);
        signout.setContentAreaFilled(false);
        signout.setFocusPainted(false);
        signout.setOpaque(false);
    }//GEN-LAST:event_signoutMouseExited

    private void jloginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jloginbtnMouseClicked
        Panel_main pnm = new Panel_main();
        pnm.setVisible(true);
        pnm.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jloginbtnMouseClicked

    private void jloginbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jloginbtnMouseEntered
        jloginbtn.setForeground(Color.red);
    }//GEN-LAST:event_jloginbtnMouseEntered

    private void jloginbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jloginbtnMouseExited
       jloginbtn.setForeground(Color.blue);
    }//GEN-LAST:event_jloginbtnMouseExited

    private void registeredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredActionPerformed
        Registered rgt = new Registered();
        rgt.setLocationRelativeTo(null);
        rgt.setVisible(true);
        
    }//GEN-LAST:event_registeredActionPerformed

    private void evaluationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluationActionPerformed
        evaluation epf = new evaluation();
        epf.setVisible(true);
        epf.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_evaluationActionPerformed

    private void coursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesActionPerformed
        courses crs = new courses();
        JDialog dialog = new JDialog(crs,"Course",true);
        dialog.getContentPane().add(crs.getPanel());
        crs.getPanel().setPreferredSize(new Dimension(660,446));
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    }//GEN-LAST:event_coursesActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        status st = new status();
        st.setVisible(true);
    }//GEN-LAST:event_statusActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_page_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_page_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_page_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_page_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_page_panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton courses;
    private javax.swing.JButton evaluation;
    private javax.swing.JLabel evaluationlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jloginbtn;
    private javax.swing.JLabel labelcon;
    private javax.swing.JLabel powerlbl;
    private javax.swing.JButton register;
    private javax.swing.JButton registered;
    private javax.swing.JLabel registeredlbl;
    private javax.swing.JButton setting;
    private javax.swing.JLabel settinglbl;
    private javax.swing.JButton signout;
    private javax.swing.JLabel signoutlbl;
    private javax.swing.JButton status;
    // End of variables declaration//GEN-END:variables

    private void setPreferredSize(int i, int i0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
